apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ferry-detection.fullname" . }}
  labels:
    {{- include "ferry-detection.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ferry-detection.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ferry-detection.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence.certs.enabled }}
            - name: {{ .Values.persistence.certs.volumeName }}
              mountPath: {{ .Values.persistence.certs.mountPath }}
              readOnly: true
            {{- end }}
      volumes:
        {{- if .Values.persistence.certs.enabled }}
        - name: {{ .Values.persistence.certs.volumeName }}
          secret:
            secretName: {{ .Values.persistence.certs.secretName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
