image:
  repository: harbor.i2cv.io/cosmichorizon/ferry_detector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

resources:
  # Limits and requests for the large YOLO model
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 2000m
    memory: 4Gi

existingSecret:
  name: ferry-secrets

secretMount:
  enabled: true
  mountPath: /etc/certs
  items:
    - key: dod_CA.pem
      path: dod_CA.pem
    - key: decrypted.key
      path: decrypted.key
    - key: justcrt.crt
      path: justcrt.crt

secretEnv:
  enabled: true
  keys:
    - CHATKEY
    - TEST_LOCAL

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecrets:
  - name: s-hxl2n